In [85]:
import numpy as np

In [86]:
# Concatenation
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

arr = np.concat((arr1, arr2))
arr = np.append(arr, 9)
arr = np.insert(arr, 0, 0)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
arr = np.delete(arr, 7) # Returns new array
arr

array([0, 1, 2, 3, 4, 5, 6, 8, 9])

In [88]:
# Delete in 2D array
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

arr_2d = np.delete(arr_2d, 1, axis=0)
arr_2d

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [89]:
arr_2d = np.delete(arr_2d, 2, axis=1)
arr_2d

array([[ 1,  2,  4],
       [ 9, 10, 12],
       [13, 14, 16]])

In [90]:
arr = np.hstack((arr1, arr2))
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [91]:
arr = np.vstack((arr1, arr2))
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [92]:
# Splitting
# Horizontal
np.split(arr, 2, axis=0)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [93]:
# Vertical
np.split(arr, 2, axis=1)

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [94]:
import math

arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16],
                   [1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [95]:

partition_1 = math.floor(0.6 * len(arr_2d))
partition_2 = partition_1 + math.floor(0.2 * len(arr_2d))

partition_list = [partition_1, partition_2]

res = np.split(ary=arr_2d, indices_or_sections=partition_list, axis=0)

# Print all the partitions
for part in res:
    print(f"{part}\n")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[1 2 3 4]]

[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]



In [96]:
# Broadcasting
prices = [100,200,300]
prices = np.array(prices)

discount = 10 # Percent
final_prices  = prices - (prices * (discount / 100))

final_prices

array([ 90., 180., 270.])

In [97]:
matrix = np.array([[1,2,3],
                   [4,5,6]])
vector = np.array([10,11,12])

matrix + vector

array([[11, 13, 15],
       [14, 16, 18]])

In [98]:
list1 = np.array(range(1, 10000 + 1))
list2 = np.array(range(1, 10000 + 1))

list3 = list1 + list2
list3

array([    2,     4,     6, ..., 19996, 19998, 20000], shape=(10000,))

In [99]:
arr = np.array([1,2,3,4,5,6,7,8, np.nan])
np.isnan(arr)

array([False, False, False, False, False, False, False, False,  True])

In [100]:
print(np.nan == np.nan) # we cannot directly compare two np.nan values

False


In [101]:
res = np.nan_to_num(arr, nan=9)
res

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
res[3] = np.inf
res[7] = -np.inf

res[5] = np.nan

np.isinf(res)

array([False, False, False,  True, False, False, False,  True, False])

In [103]:
res = np.nan_to_num(x=res, posinf=100, neginf=-100, nan=0)
res

array([   1.,    2.,    3.,  100.,    5.,    6.,    7., -100.,    9.])